In [15]:
import pandas as pd
import pymongo
import json

In [2]:
'read the fitbitdata.csv and store the dataframe'
fitbit_df =pd.read_csv("F:\ineuron FSDS\pandas practice\Task 31-07-2022\FitBitdata.csv")

In [4]:
fitbit_df.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,3/25/2016,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,3/26/2016,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,3/27/2016,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,3/28/2016,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,3/29/2016,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

In [5]:
# The issue regarding bulk upload to mongoDB was that it was creating a single document inside our collection.
# So here the trick is while converting CSV to JSON we need to mention orient as records. Thats it. Each record will be
# a separate document in mondodb.

In [6]:
fitbit_df.to_json(r"F:\ineuron FSDS\pandas practice\Task 31-07-2022\new_FitBitdat.json",orient="records")

In [8]:
df_read_json = pd.read_json(r"F:\ineuron FSDS\pandas practice\Task 31-07-2022\new_FitBitdat.json")

In [10]:
df_read_json.head() # so the conversion is OK.

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,3/25/2016,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,3/26/2016,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,3/27/2016,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,3/28/2016,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,3/29/2016,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

In [11]:
# load the JSON, and store it in data.
# P.S - the data here is stored as list, unlike dictionary if the JSON was not specified as records earlier.

with open(r"F:\ineuron FSDS\pandas practice\Task 31-07-2022\new_FitBitdat.json") as file:
    data = json.load(file)

In [13]:
data[0:5]  # the data stored in below format which we can now push to mongodb.

[{'Id': 1503960366,
  'ActivityDate': '3/25/2016',
  'TotalSteps': 11004,
  'TotalDistance': 7.1100001335,
  'TrackerDistance': 7.1100001335,
  'LoggedActivitiesDistance': 0.0,
  'VeryActiveDistance': 2.5699999332,
  'ModeratelyActiveDistance': 0.4600000083,
  'LightActiveDistance': 4.0700001717,
  'SedentaryActiveDistance': 0.0,
  'VeryActiveMinutes': 33,
  'FairlyActiveMinutes': 12,
  'LightlyActiveMinutes': 205,
  'SedentaryMinutes': 804,
  'Calories': 1819},
 {'Id': 1503960366,
  'ActivityDate': '3/26/2016',
  'TotalSteps': 17609,
  'TotalDistance': 11.5500001907,
  'TrackerDistance': 11.5500001907,
  'LoggedActivitiesDistance': 0.0,
  'VeryActiveDistance': 6.9200000763,
  'ModeratelyActiveDistance': 0.7300000191,
  'LightActiveDistance': 3.9100000858,
  'SedentaryActiveDistance': 0.0,
  'VeryActiveMinutes': 89,
  'FairlyActiveMinutes': 17,
  'LightlyActiveMinutes': 274,
  'SedentaryMinutes': 588,
  'Calories': 2154},
 {'Id': 1503960366,
  'ActivityDate': '3/27/2016',
  'TotalSteps': 12736,
  'TotalDistance': 8.529999733,
  'TrackerDistance': 8.529999733,
  'LoggedActivitiesDistance': 0.0,
  'VeryActiveDistance': 4.6599998474,
  'ModeratelyActiveDistance': 0.1599999964,
  'LightActiveDistance': 3.7100000381,
  'SedentaryActiveDistance': 0.0,
  'VeryActiveMinutes': 56,
  'FairlyActiveMinutes': 5,
  'LightlyActiveMinutes': 268,
  'SedentaryMinutes': 605,
  'Calories': 1944},
 {'Id': 1503960366,
  'ActivityDate': '3/28/2016',
  'TotalSteps': 13231,
  'TotalDistance': 8.9300003052,
  'TrackerDistance': 8.9300003052,
  'LoggedActivitiesDistance': 0.0,
  'VeryActiveDistance': 3.1900000572,
  'ModeratelyActiveDistance': 0.7900000215,
  'LightActiveDistance': 4.9499998093,
  'SedentaryActiveDistance': 0.0,
  'VeryActiveMinutes': 39,
  'FairlyActiveMinutes': 20,
  'LightlyActiveMinutes': 224,
  'SedentaryMinutes': 1080,
  'Calories': 1932},
 {'Id': 1503960366,
  'ActivityDate': '3/29/2016',
  'TotalSteps': 12041,
  'TotalDistance': 7.8499999046,
  'TrackerDistance': 7.8499999046,
  'LoggedActivitiesDistance': 0.0,
  'VeryActiveDistance': 2.1600000858,
  'ModeratelyActiveDistance': 1.0900000334,
  'LightActiveDistance': 4.6100001335,
  'SedentaryActiveDistance': 0.0,
  'VeryActiveMinutes': 28,
  'FairlyActiveMinutes': 28,
  'LightlyActiveMinutes': 243,
  'SedentaryMinutes': 763,
  'Calories': 1886}]

In [16]:
#bulk upload to mongodb

client = pymongo.MongoClient("mongodb+srv://achowdh:failsafe@agnik0.mmtem.mongodb.net/?retryWrites=true&w=majority")
db = client.test

db = client['fitbit']
collection = db['newfitbitdata']
collection.insert_many(data)

In [17]:
#the above push was success. Lets try to fetch some collections from mongodb

In [92]:
record_ex1 = collection.find({"Id": 1503960366})

In [93]:
list_record =[]
for i in record_ex1:
    list_record.append(i)

In [96]:
list_record[:2]

[{'_id': ObjectId('62f9e63b010ed0fc641e4066'),
  'Id': 1503960366,
  'ActivityDate': '3/25/2016',
  'TotalSteps': 11004,
  'TotalDistance': 7.1100001335,
  'TrackerDistance': 7.1100001335,
  'LoggedActivitiesDistance': 0.0,
  'VeryActiveDistance': 2.5699999332,
  'ModeratelyActiveDistance': 0.4600000083,
  'LightActiveDistance': 4.0700001717,
  'SedentaryActiveDistance': 0.0,
  'VeryActiveMinutes': 33,
  'FairlyActiveMinutes': 12,
  'LightlyActiveMinutes': 205,
  'SedentaryMinutes': 804,
  'Calories': 1819},
 {'_id': ObjectId('62f9e63b010ed0fc641e4067'),
  'Id': 1503960366,
  'ActivityDate': '3/26/2016',
  'TotalSteps': 17609,
  'TotalDistance': 11.5500001907,
  'TrackerDistance': 11.5500001907,
  'LoggedActivitiesDistance': 0.0,
  'VeryActiveDistance': 6.9200000763,
  'ModeratelyActiveDistance': 0.7300000191,
  'LightActiveDistance': 3.9100000858,
  'SedentaryActiveDistance': 0.0,
  'VeryActiveMinutes': 89,
  'FairlyActiveMinutes': 17,
  'LightlyActiveMinutes': 274,
  'SedentaryMinutes': 588,
  'Calories': 2154}]

In [84]:
df=pd.DataFrame(d) # convert the same to DataFrame

In [85]:
df

,_id,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,62f9e63b010ed0fc641e4066,1503960366,3/25/2016,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,62f9e63b010ed0fc641e4067,1503960366,3/26/2016,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,62f9e63b010ed0fc641e4068,1503960366,3/27/2016,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,62f9e63b010ed0fc641e4069,1503960366,3/28/2016,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,62f9e63b010ed0fc641e406a,1503960366,3/29/2016,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886
5,62f9e63b010ed0fc641e406b,1503960366,3/30/2016,10970,7.16,7.16,0.0,2.36,0.51,4.29,0.0,30,13,223,1174,1820
6,62f9e63b010ed0fc641e406c,1503960366,3/31/2016,12256,7.86,7.86,0.0,2.29,0.49,5.04,0.0,33,12,239,820,1889
7,62f9e63b010ed0fc641e406d,1503960366,4/1/2016,12262,7.87,7.87,0.0,3.32,0.83,3.64,0.0,47,21,200,866,1868
8,62f9e63b010ed0fc641e406e,1503960366,4/2/2016,11248,7.25,7.25,0.0,3.00,0.45,3.74,0.0,40,11,244,636,1843
9,62f9e63b010ed0fc641e406f,1503960366,4/3/2016,10016,6.37,6.37,0.0,0.91,1.28,4.18,0.0,15,30,314,655,1850
10,62f9e63b010ed0fc641e4070,1503960366,4/4/2016,14557,9.80,9.80,0.0,3.39,0.70,5.69,0.0,43,18,285,757,2030
11,62f9e63b010ed0fc641e4071,1503960366,4/5/2016,14844,9.73,9.73,0.0,2.94,0.76,6.04,0.0,36,18,341,736,2083
12,62f9e63b010ed0fc641e4072,1503960366,4/6/2016,11974,7.67,7.67,0.0,2.04,0.48,5.15,0.0,27,12,228,1173,1861
13,62f9e63b010ed0fc641e4073,1503960366,4/7/2016,10198,6.44,6.44,0.0,1.20,0.79,4.45,0.0,17,20,195,1208,1755
14,62f9e63b010ed0fc641e4074,1503960366,4/8/2016,12521,7.94,7.94,0.0,3.31,0.90,3.74,0.0,46,22,212,1160,1895
15,62f9e63b010ed0fc641e4075,1503960366,4/9/2016,12432,8.10,8.10,0.0,2.59,0.59,4.92,0.0,32,15,248,738,1883
16,62f9e63b010ed0fc641e4076,1503960366,4/10/2016,10057,6.98,6.98,0.0,4.00,0.49,2.48,0.0,44,13,168,737,1755
17,62f9e63b010ed0fc641e4077,1503960366,4/11/2016,10990,7.26,7.26,0.0,2.04,0.57,4.65,0.0,26,14,216,855,1811
18,62f9e63b010ed0fc641e4078,1503960366,4/12/2016,224,0.14,0.14,0.0,0.00,0.00,0.13,0.0,0,0,9,32,50